
//token actions
export const SET_TOKEN = 'SET_TOKEN';

//course files actions
export const SET_COURSE_FILES = 'SET_COURSE_FILES';


//lecture manifest actions
export const SET_LECTURE_MANIFEST = 'SET_LECTURE_MANIFEST';

//lecture time actions
export const SET_LECTURE_TIME = 'SET_LECTURE_TIME';

//calendar form actions
export const calFormConstants = {
    SET_CAL_ORIGINAL_CAL: 'SET_CAL_ORIGINAL_CAL',
    SET_CAL_SHOW_RECUR: 'SET_CAL_SHOW_RECUR',
    SET_CAL_MODAL_STATE: 'SET_CAL_MODAL_STATE',
    SET_CAL_MESSAGE_STATE: 'SET_CAL_MESSAGE_STATE',
    SET_CAL_MESSAGE_TEXT: 'SET_CAL_MESSAGE_TEXT',
    SET_CAL_MESSAGE_TITLE: 'SET_CAL_MESSAGE_TITLE',
    SET_CAL_EVENTS: 'SET_CAL_EVENTS',
    SET_CAL_S_DATE: 'SET_CAL_S_DATE',
    SET_CAL_E_DATE: 'SET_CAL_E_DATE',
    SET_CAL_S_TIME: 'SET_CAL_S_TIME',
    SET_CAL_E_TIME: 'SET_CAL_E_TIME',
    SET_CAL_REPEAT_DAYS: 'SET_CAL_REPEAT_DAYS',
    SET_CAL_RECURRENCE: 'SET_CAL_RECURRENCE',
    SET_CAL_EXCLUDE_DATES: 'SET_CAL_EXCLUDE_DATES',
    SET_CAL_INCLUDE_DATES: 'SET_CAL_INCLUDE_DATES',
    SET_CAL_DESCRIPTION: 'SET_CAL_DESCRIPTION',
    SET_CAL_LOC: 'SET_CAL_LOC',
    SET_CAL_COURSE_ID: 'SET_CAL_COURSE_ID',
    CLEAR_FORM: 'CLEAR_FORM'
}

//lecture delete actions
export const deleteLectureConstants = {
    SET_DELETE_LECTURE: 'SET_DELETE_LECTURE',
    CLEAR_DELETE_LECTURE: 'CLEAR_DELETE_LECTURE'
}

export const lectureImageConstants = {
    SET_LECTURE_IMAGE: 'SET_LECTURE_IMAGE',
    CLEAR_LECTURE_IMAGE: 'CLEAR_LECTURE_IMAGE',
    SET_IMAGE_TYPE: 'SET_IMAGE_TYPE',
    SET_INDEX: 'SET_INDEX'
}

export const instructorSettingsConstants = {
    SET_INSTRUCTOR_PAGE: 'SET_INSTRUCTOR_PAGE',
    CLEAR_INSTRUCTOR_PAGE: 'CLEAR_INSTRUCTOR_PAGE',
    SET_STATUS_MESSAGE: 'SET_STATUS_MESSAGE',
    CLEAR_STATUS_MESSAGE: 'CLEAR_STATUS_MESSAGE'
}

export const lectureUploadConstants = {
    SET_LECTURE_FILE: 'SET_LECTURE_FILE',
    SET_LECTURE_DATE: 'SET_LECTURE_DATE',
    CLEAR_UPLOAD: 'CLEAR_UPLOAD'
}
